### ISSUE TITLE
ChildRecyclerView 滑动问题

### ISSUE THREAD

**Issue by daiwenbo88** [xmuSistone/PersistentRecyclerView#10]
ParentRecyclerView 中有这么一段代码 当ChildRecyclerView 中item 是不规则的时候 computeVerticalScrollOffset()获取的滚动高度不准确

 `override fun onNestedPreScroll(target: View, dx: Int, dy: Int, consumed: IntArray, type: Int) {
        if (target is ChildRecyclerView) {
            // 下面这一坨代码的主要目的是计算consumeY
            var consumeY = dy
            val childScrollY = target.computeVerticalScrollOffset()
       }
     ...........
}`

**Comment by xmuSistone** [comment]
@daiwenbo88 附带的影响是？

**Comment by Xumingrong** [comment]
@xmuSistone  在华为 mate 20  Android 10中，demo测试：FeedsFragment列表添加点击事件后，父列表会不自然的往下滑动一段距离。
![image](https://user-images.githubusercontent.com/14052891/104691881-ff246c80-5741-11eb-91aa-063d88aaa752.png)

**Comment by xmuSistone** [comment]
@Xumingrong @daiwenbo88 华为手机适配问题已解，请拉最新代码试试；如果还有问题，请再反馈
