### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by DongMoving** [xmuSistone/PersistentRecyclerView#2]
作者写的这个非常棒,滑动效果也非常牛逼,滑动置顶的如京东的tablayout吧变换样式这个该怎么处理呢

**Comment by xmuSistone** [comment]
@DongMoving TabLayout也是支持的，你直接在xml里面换掉就可以，这个对PersistentRecyclerView是完全不影响的。后面有空我也改下

**Comment by DongMoving** [comment]
我的意思是,京东的头部置顶在滑动的时候这个头部样式有所变化,这个有没有暴露什么方法来修改这个东西,上滑时只有一行,下拉时两行,做这个变换样式,我看没有提供暴露方法啊

**Comment by DongMoving** [comment]
看了好多仿京东首页效果的例子,无疑你的是效果最好的一个,作者真棒

**Comment by xmuSistone** [comment]
@DongMoving 明白，TabLayout吸顶时加上回调，周末我弄下！至于TabLayout样式问题，此库就不着重去写了，你们自己玩的开心就行😅

**Comment by DongMoving** [comment]
嗯嗯,多谢了啊

**Comment by xmuSistone** [comment]
@DongMoving 我提了新代码，监听是否“吸顶”可以这样用：
```java
recyclerView.setStickyListener {
      // 吸顶的flag就是it
      val isStickyTop: Boolean = it
      // TO DO: 其它处理
}
```
