### ISSUE TITLE
可以用support包下面的recyclerView跟viewPager吗？

### ISSUE THREAD

**Issue by hzyxym** [xmuSistone/PersistentRecyclerView#3]
问题：可以用support包下面的recyclerView跟viewPager吗？
描述：我换完了support包下的recyclerView跟viewPager（包括反射的一些方法修改），我的项目发现parentRecyclerView滑动很快的时候是没问题的，如果parentRecyclerView跟childRecyclerView同时在屏幕时，滑动childRecyclerView时只滑动childRecyclerView，而外层不动；
分析：不知道是不是我用的不是androidx下面的recycleview跟viewpager导致的，还有ParentRecycleView我用了淘宝的v-layout的VirtualLayoutManager；希望能得到作者的指点，同时感谢作者提供的方案。

**Comment by xmuSistone** [comment]
@hzyxym 可以用support下面的RecyclerView和ViewPager；
至于你遇到的问题，主要是内联滑动没处理好，可以这样来： 
1. ParentRecyclerView实现NestedScrillingParent2，
2. onStartNestedScroll返回true；
3. 在onNestedPreScroll中处理好内联滑动细节；

至于VirtualLayoutManager，应该没关系，它只负责layout的事情，内联和Touch的逻辑，整体还是由Nested机制来处理的。
