### ISSUE TITLE
配合SwipeRefreshLayout或者SmartRefreshLayout出现下拉圆圈偶尔无法正常回弹的情况。

### ISSUE THREAD

**Issue by zjxuzhj** [xmuSistone/PersistentRecyclerView#4]
![图片](https://user-images.githubusercontent.com/17846505/91662489-57512e00-eb15-11ea-954e-1a4be842d67d.jpg)

感觉有点炸了。不知道为什么。。是recyclerview 传递了太大的滑动速度给 下拉刷新控件吗

**Comment by xmuSistone** [comment]
demo也有此类问题？

**Comment by xmuSistone** [comment]
我试了下是没问题的。你检查下自己的代码逻辑，猜测是你业务代码导致
