### ISSUE TITLE
华为Mate 20手机的bug

### ISSUE THREAD

**Issue by Xumingrong** [xmuSistone/PersistentRecyclerView#5]
你好，我在华为Mate 20手机上(EMUI10.1.0、Androd 10),页面滑到最底部，点击屏幕，页面会不自然的向上滚动一段距离。不知道这是什么原因。

**Comment by xmuSistone** [comment]
能描述清楚一些么？或者截个视频？

**Comment by lennyup** [comment]
我这也有同样的问题 android 10系统，望大佬看看

**Comment by xmuSistone** [comment]
@lennyup @Xumingrong 我试了安卓10是没问题的啊，Mate 20也没问题。 你们是改了代码么？还是直接跑的demo？

**Comment by lennyup** [comment]
@xmuSistone demo也是有这个问题的，就是 在不吸顶的时候按住上滑或者下滑，就会自动滚一段距离

**Comment by lennyup** [comment]
华为手机有这个问题

**Comment by youlookwhat** [comment]
@xmuSistone 华为P30复现了，大佬能不能修复下

**Comment by xmuSistone** [comment]
谁能发个截屏视频？ 120809170@qq.com

**Comment by lennyup** [comment]
@xmuSistone 大佬发你了

**Comment by youlookwhat** [comment]
@xmuSistone 已发

**Comment by xmuSistone** [comment]
我看下

**Comment by youlookwhat** [comment]
过来再催一催。。

**Comment by xmuSistone** [comment]
@youlookwhat 我试了几台安卓10.0的手机，发现都没问题；

请问，这是稳定复现的么？还是有一定的规律性？

PS： 跳跃问题，归结于内联滑动，我初步怀疑是ParentRecyclerView. onNestedPreScroll那里出问题了，猜测是华为手机的computeVerticalScrollOffset有问题；

**Comment by youlookwhat** [comment]
我估计不一定是安卓10的问题，华为感觉是必现，我用公司的两台华为手机都复现了

**Comment by xmuSistone** [comment]
我找华为机试下

**Comment by youlookwhat** [comment]
恩恩  麻烦啦

**Comment by youlookwhat** [comment]
华为 且为 Android10 的手机能复现，公司另一台华为android9是好的

**Comment by youlookwhat** [comment]
比较急，希望能尽快解决。。(华为的Android10系统)

**Comment by xmuSistone** [comment]
@youlookwhat @lennyup @Xumingrong 华为手机的问题已经FIX，DEMO APK也已更新 - 参看今天的两次commit

问题原因：ChildRecyclerView消费Touch事件发起内联滑动，但是却被ParentRecyclerView拦截；华为手机对Touch拦截的阈值较小，也就是说拦截很灵敏；

PS：感谢各位发现此类问题

**Comment by lennyup** [comment]
在action_down处设置FLAG_DISALLOW_INTERCEPT这个flag不能阻断ParentRecyclerView拦截事件，因为dispatchTouchEvent的时候会重置这个值吧。
（ps：我刚装了新的包,问题还是存在，操作步骤：在有ChildRecyclerView的时候点击滑动一条龙）

**Comment by youlookwhat** [comment]
@xmuSistone 很遗憾问题还存在..

**Comment by lennyup** [comment]
我觉得应该在dispathTouchEvent中进行拦截

**Comment by xmuSistone** [comment]
@lennyup 分发和拦截是两码事，你不能弄混的，onTouchEvent是谁来消费，有很严谨的设计；建议**仔细**看下相关的博客文档，touch事件的流转，水很深；

**Comment by kivenerwang** [comment]
这个问题 在华为 android 10.0 上 还存在
